# Problem 1 

In [5]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
v = np.array([5,16,4,34,56])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
print(v)
v.sort()
print(v)

[ 5 16  4 34 56]
[ 4  5 16 34 56]


# Problem 2

In [146]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
import numpy as np
print("Soru 1")
n1 = np.array([10,15,30,45,60])
print(n1)
print("------------")
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
print("Soru 2")
n2 = np.arange(5,16,1)
print(n2)
print("------------")
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
print("Soru 3")
n3 = np.arange(50,101,5)
print(n3)
print("------------")
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
print("Soru 4")
n4 = np.zeros((3,5))
print(n4)
print("------------")
# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
print("Soru 5")
n5 = np.ones((3,5))
print(n5)
print("------------")
print("Soru 6")
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
n6 = np.linspace(0,100,5) #######   Aklımda soru var
print(n6)
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
print("Soru 7")
n7= np.random.randint(10, 30, 5)
n7.sort() #Ekstra olarak sıralamak istedim :) 
print(n7)
print("-------------")
print("Soru 8")
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
n8 = np.random.normal(-1, 1, (1,10)) #Ondalıklı sayılarıda içermesini istersek randint yerine normal yazabiliriz.
n8.sort()
print(n8)
print("-------------")
n9 = np.random.randint(-1, 1, (1,10)) #Sadece tam sayılar için ise randint kısmı bu şekilde oluşur.
n9.sort()
print(n9)
print("-------------")
print("Soru 9")
print("Not:10-18.arasındaki sorular 9.sorudaki matrise göre yapılıyor.")
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
n10 = np.random.randint(10,50 ,(3,5))
print(n10)
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print("-------------")
print("Soru 10")
n11= n10.sum()
print(n11)
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print("-------------") 
print("Soru 11")
print("Liste"
    ,n10)
print("En Büyük Sayı", np.max(n10))
print("En Küçük Sayı",np.min(n10))
print("Ortalama",str(n11//15))
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print("-------------")
print("Soru 12")
print("En Büyük Sayının İndeksi", np.argmax(n10))
# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
print("-------------")
print("Soru 13")
n12 = np.arange(10,21,1)
print(n12[0:3])
# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print("-------------")
print("Soru 14")
n13 = n12[::-1]
print(n13)
# 15- Üretilen matrisin ilk satırını seçiniz.
print("-------------")
print("Soru 15")
n14_alt = n10[0:1,0:5]
print(n14_alt)

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print("-------------")
print("Soru 16")
n15_alt = n10[1:2]
print(n15_alt[:,2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print("-------------")
print("Soru 17")
n16_alt = n10[:,0]
print(n16_alt)
# 18- Üretilen matrisin her bir elemanının karesini alınız.
print("-------------")
print("Soru 18")
print(np.multiply(n10,n10))
# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
print("-------------")
print("Soru 19")
n17 = np.random.randint(-50,50 ,(3,5))
print("Liste"
       ,n17)
print("Sadece Pozitif Elemanlar",n17[n17>0])


Soru 1
[10 15 30 45 60]
------------
Soru 2
[ 5  6  7  8  9 10 11 12 13 14 15]
------------
Soru 3
[ 50  55  60  65  70  75  80  85  90  95 100]
------------
Soru 4
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
------------
Soru 5
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
------------
Soru 6
[  0.  25.  50.  75. 100.]
Soru 7
[10 13 18 22 26]
-------------
Soru 8
[[-2.0573136  -1.7632119  -1.45617396 -1.4114677  -1.04573959 -0.6720013
  -0.39364208 -0.24357854 -0.17327707  0.10391943]]
-------------
[[-1 -1 -1 -1  0  0  0  0  0  0]]
-------------
Soru 9
Not:10-18.arasındaki sorular 9.sorudaki matrise göre yapılıyor.
[[45 16 23 27 49]
 [12 25 18 21 43]
 [25 30 39 24 24]]
-------------
Soru 10
421
-------------
Soru 11
Liste [[45 16 23 27 49]
 [12 25 18 21 43]
 [25 30 39 24 24]]
En Büyük Sayı 49
En Küçük Sayı 12
Ortalama 28
-------------
Soru 12
En Büyük Sayının İndeksi 4
-------------
Soru 13
[10 11 12]
-------------
Soru 14
[20 19 18 17 16 15 14 13 12 11 10]
------