# Problem 1

In [84]:
import numpy as np 

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
a = np.random.normal(0,10,(4,5))
print(a)
print("--------")

alt_a = a[0:5,0:2]
print(alt_a)
print("--------")

print(a.dtype)
print("--------")

multi = a.reshape(2,10)
print(a)
print("--------")

print(a.ndim)

[[ 10.81934974  -1.39030497  -8.03023404 -14.1936416   -0.97217094]
 [ -7.89260721  -3.65946332  -4.76172512  15.80206364  13.27594986]
 [ -8.83231425   2.15101874  14.84380387  19.85177372   8.36500324]
 [  5.11668237 -16.40436549   3.59670239   4.43803022   9.4860062 ]]
--------
[[ 10.81934974  -1.39030497]
 [ -7.89260721  -3.65946332]
 [ -8.83231425   2.15101874]
 [  5.11668237 -16.40436549]]
--------
float64
--------
[[ 10.81934974  -1.39030497  -8.03023404 -14.1936416   -0.97217094]
 [ -7.89260721  -3.65946332  -4.76172512  15.80206364  13.27594986]
 [ -8.83231425   2.15101874  14.84380387  19.85177372   8.36500324]
 [  5.11668237 -16.40436549   3.59670239   4.43803022   9.4860062 ]]
--------
2


# Problem 2

In [129]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
b =np.arange(1,10,2)

matrix = b[:4].reshape(2,2)
print(matrix) 
#Kalan son elemanı nasıl koyabileceğimi bulamadım.
# 2 - Oluşturduğunuz matrisi parçalayın
print(np.split(b,[1,3]))
# 3 - Parçalanmış matrisleri birleştirin
print(np.concatenate([b]))


[[1 3]
 [5 7]]
[array([1]), array([3, 5]), array([7, 9])]
[1 3 5 7 9]


# Problem 3

In [113]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
c =np.arange(5,100,2)

sec =np.random.choice(c.size, 10, replace= False)
#10 sayıyı seçmek için choice komutunu kullandık.
#c.size eleman sayısı ve seçilmesi istediğimiz eleman sayısını yazdık
#replace=False aynı elemanın birden fazla seçilmemesini sağlamak için kullandık.
secilen = c[sec]

matrix = sec.reshape(2,5) #2x5'lik bir matris olarak koyduk.
print(matrix)

# 2 - matris'in özelliklerini inceleyin
print("""-------------
Özellikler""")
print(matrix.shape)  # Matrisin boyutu
print(matrix.size)   # Eleman sayısı
print(matrix.dtype)  # Veri tipi


[[43 24 46 17 36]
 [42 47 37  9 12]]
-------------
Özellikler
(2, 5)
10
int32
