### Bu hafta öğrenilicek kısımlar.
Numpy Nedir ve Neden Kullanıyoruz?  
Temel Numpy Özellikleri ve Detayları  
 


### Numpy
- Numpy sayısal işlemleri hızlı yapmak için C dili ile yazılmış bir Python kütüphanesidir.
- Veri analizinde kullanılır.
- Bilgisayara kurmak için `pip install numpy` komutu ile kurulabilir.
- Bilimsel hesaplamalar için kullanılır.
- Arraylar/çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı işlemler yapılabilir.
- Temelleri 1995 yılında atıldı. Ama nihai olarak 2005 yılında Travis Oliphant tarafından hayata geçmiştir.
- Listelere benzerdir. Fakat verimli veri saklama ve vektör işlemleri için Numpy kullanılır.

## Neden Numpy?

In [3]:
# Klasik yöntem
a = [1,2,3,4]
b = [2,3,4,5]
ab = []
for i in range(0,len(a)):
    ab.append(a[i]* b[i])
print(ab)

[2, 6, 12, 20]


In [35]:
# Numpy ile
import numpy as np
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
print(a*b)

[ 2  6 12 20]


.reshape() fonksiyonu ile arraylerin boyutlarını değiştirebiliriz.

In [3]:
x = np.array([1,2,3,4,5,6,7,8,9])
multi =x.reshape(3,3)
print(multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


.shape ile arraylerin boyutlarını öğrenebiliriz.

In [4]:
print(multi.shape)

(3, 3)


.ndim ile arraylerin boyut sayısını öğrenebiliriz.

In [5]:
print(x.ndim)

1


In [6]:
print(multi.ndim)

2


## Temel Numpy Özellikleri

### Birleştirme (Concatenation)
* .concatenate() fonksiyonu ile birleştirme yapabiliriz.


In [4]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
print(np.concatenate([x,y]))

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
z = np.array([11,12,13,14,15])
print(np.concatenate([x,y,z]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [8]:
a = np.array(([1,2,3],[4,5,6]))
print(np.concatenate([a,a]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


axis = 0 satır bazında birleşitrme yapar.  
axis = 1 ise sütun bazında birleştirme yapar.  

In [10]:
print(np.concatenate([a,a], axis =1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [11]:
print(np.concatenate([a,a], axis =0))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


### Array Ayırma (Splitting)
* .split() fonksiyonu ile array ayırma yapabiliriz.

In [16]:
m = np.array(([1,2,3,92,92,3,2,1]))
print(np.split(m,[3,5]))#3. Eleman ile 5.Eleman arasında bir ayırma işlemi gerçekleşir.

[array([1, 2, 3]), array([92, 92]), array([3, 2, 1])]


* vsplit() fonksiyonu ile arrary yatay olarak ayırma yapabiliriz.

In [18]:
n = np.arange(16).reshape(4,4)
np.vsplit(n,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

* hsplit() fonksiyonu ile arrary dikey olarak ayırma yapabiliriz.

In [20]:
np.hsplit(n,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

np.arange()  
* Belli bir aralıkta sayıları oluşturmak için kullanılır.
* np.arange(start,stop,stop)


In [23]:
n = np.arange(3,12,2)
print(n)

[ 3  5  7  9 11]


np.zeros()  
* 0'lardan oluşan bir numpy dizisi oluşturulması için kullanılır.

In [25]:
n2 = np.zeros(5)
print(n2)

[0. 0. 0. 0. 0.]


np.ones()  
* 1'lardan oluşan bir numpy dizisi oluşturulması için kullanılır.

In [26]:
n3 = np.ones(5)
print(n3)

[1. 1. 1. 1. 1.]


np.linspace()  
* Belli bir aralıkta sayıları oluşturmak için kullanılır.
* np.linspace(başlangıç, bitiş, bölünecek aralık)

In [27]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [28]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [30]:
np.random.randint(2,22) #Rastgele sayı veriyor aralıktan.

16

In [31]:
npArray = np.arange(50)
npMulti = npArray.reshape(5,10)
print(npMulti.sum(axis=1)) # Tüm elemanları topla komutu

[ 45 145 245 345 445]


### Numpy Array'in Özellikleri
* ndim : Boyut sayısı
* shape : Boyut bilgisi
* size : Toplanan eleman sayısı
* dtype : Veri tipi

In [37]:
a = np.random.randint(10, size=10)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

1
(10,)
10
int32


### Array Sıralama(Sorting)
* Array sıralama işlemleri yapmak için numpy kütüphanesinde yer alan sort() fonksiyonu kullanılır.

In [40]:
v = np.array([8,24,232,12,5,42,55])
print(v)
v.sort()
print(v)

[  8  24 232  12   5  42  55]
[  5   8  12  24  42  55 232]


In [45]:
m = np.random.normal(20,5,(3,3))# 20 ile 5 arasında random sayıları 3'e 3'lük şekilde oluşturur.
print(m)

[[18.0319542  13.17951098 27.31447948]
 [18.69360632 19.46728554 17.34094291]
 [24.760955   19.96617058 13.19131093]]


In [49]:
print(np.sort(m,  axis = 1))

[[13.17951098 18.0319542  27.31447948]
 [17.34094291 18.69360632 19.46728554]
 [13.19131093 19.96617058 24.760955  ]]


In [48]:
print(np.sort(m, axis = 0))

[[18.0319542  13.17951098 13.19131093]
 [18.69360632 19.46728554 17.34094291]
 [24.760955   19.96617058 27.31447948]]


### Index ile Elemanlara Erişmek
* Aynı listelerde olduğu gibi index ile elemanlara erişebiliriz.

In [4]:
import numpy as np
a = np.random.randint(10, size = 10)
print(a[0])
print(a)

0
[0 8 9 1 7 6 2 8 7 8]


In [53]:
a = np.random.randint(10, size = 10)
print(a[-1])

0


In [54]:
a[0] = 100
print(a[0])

100


In [55]:
x = np.random.randint(10,size= (3,5))
print(x)

[[9 9 7 7 8]
 [2 3 1 5 0]
 [2 0 1 2 9]]


### Slicing ile Elemanlara Erişmek(Array Alt Kümesine Erişmek)
* bir liste veya dizinin belirli bir bölümünü seçmek için kullanılır. Python'da bu, oldukça yaygın ve kullanışlı bir işlemdir.

In [ ]:
# start: Dilimin başlayacağı indeks.
# end: Dilimin sona ereceği indeks (bu indeks dahil edilmez).
# step: Her seferinde kaç adım atlanacağı.
list[start:end:step]

Başlangıç veya Bitiş Belirtilmezse  
  
Başlangıç belirtilmezse, dilimleme 0. indeksten başlar.  


In [71]:
a= np.arange(20,30)
print(a)

[20 21 22 23 24 25 26 27 28 29]


In [77]:
print(a[0:3])
print("-------")
print(a[:3])
print("-------")
print(a[3:])
print("-------")
print(a[1::2])
print("-------")
print(a[0::2])

[20 21 22]
-------
[20 21 22]
-------
[23 24 25 26 27 28 29]
-------
[21 23 25 27 29]
-------
[20 22 24 26 28]


Listeyi tersine çevirmek için -1 kullanılırız.

In [ ]:
reversed_numbers = numbers[::-1]  # [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

Not: Python listeleri mutable (değiştirilebilir) olduğu için, dilimleme ile alınan alt kümeyi değiştirmek tüm listeyi etkilemez.

In [66]:
b = np.random.randint(10, size =[5,5])
print(b)

[[3 4 1 3 1]
 [9 2 7 9 6]
 [4 2 8 7 1]
 [2 0 4 6 0]
 [6 0 2 9 3]]


In [78]:
print(b[:,0]) #,0 demek 0. sutundaki elemanları al anlamına gelir.

[3 9 4 2 6]


In [68]:
print(b[:,1])

[4 2 2 0 0]


In [79]:
print(b[0,:]) # Bu da 0.sutundaki elemanları al anlamına gelir.

[3 4 1 3 1]


In [81]:
print(b[::2,::2]) #0. indeksten itibaren 2 şer fark ile satırdaki elemanları al ve her satırdan 2 şer atlayarak ilk kısmı yapmaya devam et.

[[3 1 1]
 [4 8 1]
 [6 2 3]]


### Alt Küme Üzerinde İşlem Yapmak

In [83]:
c = np.random.randint(10, size =[5,5])
print(c)
alt_c = c[0:3,0:2] 
alt_c

[[5 3 1 4 0]
 [2 3 7 5 4]
 [0 7 8 2 6]
 [0 4 8 7 4]
 [6 1 2 8 1]]


array([[5, 3],
       [2, 3],
       [0, 7]], dtype=int32)

### Fancy Index
* Bir liste içine bu arrayden istediğiniz indeksleri koyarak o indeksteki verileri alabiliriz.

In [84]:
v = np.arange(0,30,3)
print(v)

[ 0  3  6  9 12 15 18 21 24 27]


In [86]:
yetgen = [1,3,5]
print(v[yetgen]) # 1.index, 3.index ve 5.indexi getirdik

[ 3  9 15]


In [89]:
m = np.arange(9).reshape(3,3)
satir= np.array([0,1])
sutun= np.array([1,2])
print(m[satir,sutun])

[1 5]


### Koşullu Eleman İşlemleri

In [103]:
v = np.array([1,2,3,4,5])
print(v>3)
print("----------")
print(v[v > 3])
print("----------")
print(v[v < 3])
print("----------")
print(v[v >= 3])
print("----------")
print(v[v <= 3])
print("----------")
print(v[v != 3])
print("----------")
print(v[v == 3])

[False False False  True  True]
----------
[4 5]
----------
[1 2]
----------
[3 4 5]
----------
[1 2 3]
----------
[1 2 4 5]
----------
[3]


### Matematiksel İşlemler

In [109]:
v = np.array([1,2,3,4,5])

print(v*2)
print("----------")
print(v +2)
print("----------")
print(v * 5 / 10)
print("----------")
print(v ** 2)
print("----------")

[ 2  4  6  8 10]
----------
[3 4 5 6 7]
----------
[0.5 1.  1.5 2.  2.5]
----------
[ 1  4  9 16 25]
----------


In [118]:
print(np.subtract(v,3)) # Her birinden 3 çıkartır.
print(np.add(v,3)) # Her birine 3 ekler.
print(np.multiply(v,3)) # Her birini 3 ile çarpar.
print(np.divide(v,2)) # Her birini 2'ye böler.
print(np.power(v,2)) # Her birinin 2 üssünü alır.
print(np.mod(v,3)) # Her birinin 3'e modunu alır.
print(np.absolute(v)) # Her birinii multak değere alır.
print(np.log(10)) # log 10 değerini alır.

[-2 -1  0  1  2]
[4 5 6 7 8]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]
[1 2 0 1 2]
[1 2 3 4 5]
2.302585092994046


Bunun gibi bir sürü daha kısım mevcut. Onlara bakmak istebilirse ?np / ?numpy yazılarak ulaşılabilir

### İki Bilinmeyenli Denklem Çözümü

In [129]:
# 5*x0 + x1 = 12
# x0 + 3*x1 = 10
a =np.array([[5,1],[1,3]]) 
b =np.array([12,10]) #1.denklem ve 2.denmklem cevapları
x =np.linalg.solve(a,b)
print(x)

[1.85714286 2.71428571]
